/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.examsimulator.client.view;

import com.examsimulator.client.connector.ServerConnector;
import com.examsimulator.common.controller.StudentController;
import com.examsimulator.common.dto.StudentDTO;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lahiru Sandeepa
 */
public class RegisterStudentForm extends javax.swing.JPanel {

    /**
     * Creates new form StudentManagement
     */
    public RegisterStudentForm() {
        initComponents();
        generateId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelStudentId = new javax.swing.JLabel();
        labelStudentId1 = new javax.swing.JLabel();
        labelStudentId2 = new javax.swing.JLabel();
        labelStudentId3 = new javax.swing.JLabel();
        textStudentId = new javax.swing.JTextField();
        textStudentName = new javax.swing.JTextField();
        textNIC = new javax.swing.JTextField();
        textTelephoneNo = new javax.swing.JTextField();
        labelRegisterStudent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelStudentId.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelStudentId.setText("Student Id");

        labelStudentId1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelStudentId1.setText("Student Name");

        labelStudentId2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelStudentId2.setText("NIC");

        labelStudentId3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelStudentId3.setText("Telephone No");

        textStudentId.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStudentIdActionPerformed(evt);
            }
        });

        textStudentName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStudentNameActionPerformed(evt);
            }
        });

        textNIC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNICActionPerformed(evt);
            }
        });
        textNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNICKeyReleased(evt);
            }
        });

        textTelephoneNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textTelephoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTelephoneNoKeyReleased(evt);
            }
        });

        labelRegisterStudent.setBackground(new java.awt.Color(0, 0, 204));
        labelRegisterStudent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelRegisterStudent.setForeground(new java.awt.Color(255, 255, 255));
        labelRegisterStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegisterStudent.setText("Register Student");
        labelRegisterStudent.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 255), new java.awt.Color(0, 0, 102)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelRegisterStudent.setOpaque(true);
        labelRegisterStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegisterStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelStudentId3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textTelephoneNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelStudentId1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textStudentName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelStudentId2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNIC)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRegisterStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(382, 382, 382))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStudentId)
                    .addComponent(textStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStudentId1)
                    .addComponent(textStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStudentId2)
                    .addComponent(textNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStudentId3)
                    .addComponent(textTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(labelRegisterStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStudentIdActionPerformed
        textStudentName.requestFocus();
    }//GEN-LAST:event_textStudentIdActionPerformed

    private void textStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStudentNameActionPerformed
        textNIC.requestFocus();
    }//GEN-LAST:event_textStudentNameActionPerformed

    private void textNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNICActionPerformed
        textTelephoneNo.requestFocus();
    }//GEN-LAST:event_textNICActionPerformed

    private void labelRegisterStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegisterStudentMouseClicked
        String studentId=textStudentId.getText();
        String studentName=textStudentName.getText();
        String nic=textNIC.getText();
        int telephoneNo=Integer.parseInt(textTelephoneNo.getText());
        StudentDTO student=new StudentDTO(studentId, studentName, nic, telephoneNo);
        try {
            StudentController studentController=ServerConnector.getServerConnector().getStudentController();
            boolean isAdded=studentController.add(student);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Student register successfully!");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelRegisterStudentMouseClicked

    private void textNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNICKeyReleased
        String nic=textNIC.getText();
        nic=nic.replaceAll("[\\D&&[^v]&&[^x]]", "");
        textNIC.setText(nic);
    }//GEN-LAST:event_textNICKeyReleased

    private void textTelephoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelephoneNoKeyReleased
        String telephoneNo=textTelephoneNo.getText();
        telephoneNo=telephoneNo.replaceAll("[\\D]", "");
        textTelephoneNo.setText(telephoneNo);
    }//GEN-LAST:event_textTelephoneNoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelRegisterStudent;
    private javax.swing.JLabel labelStudentId;
    private javax.swing.JLabel labelStudentId1;
    private javax.swing.JLabel labelStudentId2;
    private javax.swing.JLabel labelStudentId3;
    private javax.swing.JTextField textNIC;
    private javax.swing.JTextField textStudentId;
    private javax.swing.JTextField textStudentName;
    private javax.swing.JTextField textTelephoneNo;
    // End of variables declaration//GEN-END:variables

    private void generateId() {
        try {
            StudentController studentController=ServerConnector.getServerConnector().getStudentController();
            String id=studentController.generateId();
            textStudentId.setText(id);
        } catch (NotBoundException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RegisterStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
