/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.examsimulator.client.view;

import com.examsimulator.client.connector.ServerConnector;
import com.examsimulator.common.controller.TestDeveloperController;
import com.examsimulator.common.observer.Subject;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lahiru Sandeepa
 */
public class TestDeveloperForm extends javax.swing.JFrame {

    TestDeveloperManagementForm testDeveloperManagementForm=new TestDeveloperManagementForm();
    ViewTestDeveloperForm viewTestDeveloperForm=new ViewTestDeveloperForm();
    /**
     * Creates new form TestDeveloperForm
     */
    public TestDeveloperForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackGround = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelBack = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();
        labelRegisterTestDeveloper = new javax.swing.JLabel();
        labelManageTestDeveloper = new javax.swing.JLabel();
        labelViewTestDeveloper = new javax.swing.JLabel();
        panelDisplay = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBackGround.setBackground(new java.awt.Color(255, 255, 255));

        panelTitle.setBackground(new java.awt.Color(153, 0, 102));

        labelTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Test Developer Form");

        labelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/examsimulator/client/image/Entypo_e75e(0)_64.png"))); // NOI18N
        labelBack.setText("jLabel1");
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExit.setText("X");
        labelExit.setOpaque(true);
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        labelMinimize.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimize.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimize.setText("-");
        labelMinimize.setOpaque(true);
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addGap(446, 446, 446))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                        .addComponent(labelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelTitle)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelExit)
                        .addComponent(labelMinimize))
                    .addComponent(labelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        labelRegisterTestDeveloper.setBackground(new java.awt.Color(204, 0, 0));
        labelRegisterTestDeveloper.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        labelRegisterTestDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        labelRegisterTestDeveloper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegisterTestDeveloper.setText("Register Test Developer");
        labelRegisterTestDeveloper.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelRegisterTestDeveloper.setOpaque(true);
        labelRegisterTestDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegisterTestDeveloperMouseClicked(evt);
            }
        });

        labelManageTestDeveloper.setBackground(new java.awt.Color(204, 0, 0));
        labelManageTestDeveloper.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        labelManageTestDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        labelManageTestDeveloper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManageTestDeveloper.setText("Manage Test Developer");
        labelManageTestDeveloper.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelManageTestDeveloper.setOpaque(true);
        labelManageTestDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageTestDeveloperMouseClicked(evt);
            }
        });

        labelViewTestDeveloper.setBackground(new java.awt.Color(204, 0, 0));
        labelViewTestDeveloper.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        labelViewTestDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        labelViewTestDeveloper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViewTestDeveloper.setText("View Test Developer");
        labelViewTestDeveloper.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelViewTestDeveloper.setOpaque(true);
        labelViewTestDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelViewTestDeveloperMouseClicked(evt);
            }
        });

        panelDisplay.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelDisplayLayout = new javax.swing.GroupLayout(panelDisplay);
        panelDisplay.setLayout(panelDisplayLayout);
        panelDisplayLayout.setHorizontalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDisplayLayout.setVerticalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBackGroundLayout = new javax.swing.GroupLayout(panelBackGround);
        panelBackGround.setLayout(panelBackGroundLayout);
        panelBackGroundLayout.setHorizontalGroup(
            panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRegisterTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelManageTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelViewTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBackGroundLayout.setVerticalGroup(
            panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackGroundLayout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackGroundLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(labelRegisterTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelManageTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelViewTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBackGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(panelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelRegisterTestDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegisterTestDeveloperMouseClicked
        panelDisplay.removeAll();
        RegisterTestDeveloperForm registerTestDeveloperForm=new RegisterTestDeveloperForm();
        registerTestDeveloperForm.setSize(panelDisplay.getSize());
        panelDisplay.add(registerTestDeveloperForm);
        panelDisplay.repaint();
        panelDisplay.revalidate();
        try {
            Subject subject=(Subject) ServerConnector.getServerConnector().getTestDeveloperController();
            subject.unregisterObserver(viewTestDeveloperForm);
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_labelRegisterTestDeveloperMouseClicked

    private void labelManageTestDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageTestDeveloperMouseClicked
        panelDisplay.removeAll();
        
        testDeveloperManagementForm.setSize(panelDisplay.getSize());
        panelDisplay.add(testDeveloperManagementForm);
        panelDisplay.repaint();
        panelDisplay.revalidate();
        try {
            Subject subject=(Subject) ServerConnector.getServerConnector().getTestDeveloperController();
            subject.unregisterObserver(viewTestDeveloperForm);
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelManageTestDeveloperMouseClicked

    private void labelViewTestDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelViewTestDeveloperMouseClicked
        panelDisplay.removeAll();        
        try {
            Subject subject=(Subject) ServerConnector.getServerConnector().getTestDeveloperController();
            subject.registerObserver(viewTestDeveloperForm);
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        viewTestDeveloperForm.setSize(panelDisplay.getSize());
        panelDisplay.add(viewTestDeveloperForm);
        panelDisplay.repaint();
        panelDisplay.revalidate();       
    }//GEN-LAST:event_labelViewTestDeveloperMouseClicked

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        new AdministratorMainForm().setVisible(true);
        dispose();
        
        try {
            TestDeveloperController testDeveloperController=ServerConnector.getServerConnector().getTestDeveloperController();            
            testDeveloperController.releaseTestDeveloper(testDeveloperManagementForm.testDeveloperId);           
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Subject subject=(Subject) ServerConnector.getServerConnector().getTestDeveloperController();
            subject.unregisterObserver(viewTestDeveloperForm);
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelBackMouseClicked

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
        try {
            TestDeveloperController testDeveloperController=ServerConnector.getServerConnector().getTestDeveloperController();            
            testDeveloperController.releaseTestDeveloper(testDeveloperManagementForm.testDeveloperId);            
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Subject subject=(Subject) ServerConnector.getServerConnector().getTestDeveloperController();
            subject.unregisterObserver(viewTestDeveloperForm);
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestDeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestDeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestDeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestDeveloperForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestDeveloperForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelManageTestDeveloper;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JLabel labelRegisterTestDeveloper;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelViewTestDeveloper;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JPanel panelDisplay;
    private javax.swing.JPanel panelTitle;
    // End of variables declaration//GEN-END:variables
}
