/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.examsimulator.client.view;

import com.examsimulator.client.connector.ServerConnector;
import com.examsimulator.common.controller.StudentController;
import com.examsimulator.common.controller.TestDeveloperController;
import com.examsimulator.common.dto.StudentDTO;
import com.examsimulator.common.dto.TestDeveloperDTO;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lahiru Sandeepa
 */
public class TestDeveloperManagementForm extends javax.swing.JPanel {

    String testDeveloperId="";
    /**
     * Creates new form StudentManagement
     */
    public TestDeveloperManagementForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTestDeveloperId = new javax.swing.JLabel();
        labelTestDeveloperName = new javax.swing.JLabel();
        labelNIC = new javax.swing.JLabel();
        labelTelephoneNo = new javax.swing.JLabel();
        textTestDeveloperId = new javax.swing.JTextField();
        textTestDeveloperName = new javax.swing.JTextField();
        textNIC = new javax.swing.JTextField();
        textTelephoneNo = new javax.swing.JTextField();
        labelModifyTestDeveloper = new javax.swing.JLabel();
        labelRemoveTestDeveloper = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelTestDeveloperId.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelTestDeveloperId.setText("Test Developer Id");

        labelTestDeveloperName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelTestDeveloperName.setText("Name");

        labelNIC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelNIC.setText("NIC");

        labelTelephoneNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        labelTelephoneNo.setText("Telephone No");

        textTestDeveloperId.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textTestDeveloperId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTestDeveloperIdActionPerformed(evt);
            }
        });

        textTestDeveloperName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textTestDeveloperName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTestDeveloperNameActionPerformed(evt);
            }
        });
        textTestDeveloperName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTestDeveloperNameKeyReleased(evt);
            }
        });

        textNIC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNICActionPerformed(evt);
            }
        });
        textNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNICKeyReleased(evt);
            }
        });

        textTelephoneNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        textTelephoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTelephoneNoKeyReleased(evt);
            }
        });

        labelModifyTestDeveloper.setBackground(new java.awt.Color(0, 0, 204));
        labelModifyTestDeveloper.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelModifyTestDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        labelModifyTestDeveloper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModifyTestDeveloper.setText("Modify Test Developer");
        labelModifyTestDeveloper.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 255), new java.awt.Color(0, 0, 102)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelModifyTestDeveloper.setOpaque(true);
        labelModifyTestDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModifyTestDeveloperMouseClicked(evt);
            }
        });

        labelRemoveTestDeveloper.setBackground(new java.awt.Color(0, 0, 204));
        labelRemoveTestDeveloper.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelRemoveTestDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        labelRemoveTestDeveloper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRemoveTestDeveloper.setText("Remove Test Developer");
        labelRemoveTestDeveloper.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 255), new java.awt.Color(0, 0, 102)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelRemoveTestDeveloper.setOpaque(true);
        labelRemoveTestDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemoveTestDeveloperMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(labelModifyTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRemoveTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTestDeveloperId, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(labelTestDeveloperName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTelephoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTelephoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                            .addComponent(textNIC)
                            .addComponent(textTestDeveloperName)
                            .addComponent(textTestDeveloperId))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTestDeveloperId)
                    .addComponent(textTestDeveloperId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTestDeveloperName)
                    .addComponent(textTestDeveloperName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNIC)
                    .addComponent(textNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelephoneNo)
                    .addComponent(textTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModifyTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRemoveTestDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textTestDeveloperIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTestDeveloperIdActionPerformed
        searchTestDeveloperById();
    }//GEN-LAST:event_textTestDeveloperIdActionPerformed

    private void textTestDeveloperNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTestDeveloperNameActionPerformed
        textNIC.requestFocus();
    }//GEN-LAST:event_textTestDeveloperNameActionPerformed

    private void textNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNICActionPerformed
        textTelephoneNo.requestFocus();
    }//GEN-LAST:event_textNICActionPerformed

    private void labelModifyTestDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifyTestDeveloperMouseClicked
        String testDeveloperId=textTestDeveloperId.getText();
        String testDeveloperName=textTestDeveloperName.getText();
        String nic=textNIC.getText();
        int telephoneNo=Integer.parseInt(textTelephoneNo.getText());
        TestDeveloperDTO testDeveloper=new TestDeveloperDTO(testDeveloperId, testDeveloperName, nic, telephoneNo);
        try {
            TestDeveloperController testDeveloperController=ServerConnector.getServerConnector().getTestDeveloperController();
            boolean isModify=testDeveloperController.modifyTestDeveloper(testDeveloper);
            if (isModify) {
                JOptionPane.showMessageDialog(this, "Test developer detail modify successfully!");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                TestDeveloperController testDeveloperController=ServerConnector.getServerConnector().getTestDeveloperController();
                testDeveloperController.releaseTestDeveloper(testDeveloperId);
            } catch (NotBoundException ex) {
                Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_labelModifyTestDeveloperMouseClicked

    private void textTestDeveloperNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTestDeveloperNameKeyReleased
        searchTestDeveloperByName();
    }//GEN-LAST:event_textTestDeveloperNameKeyReleased

    private void labelRemoveTestDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemoveTestDeveloperMouseClicked
        String testDeveloperId=textTestDeveloperId.getText();
        try {
            TestDeveloperController testDeveloperController=ServerConnector.getServerConnector().getTestDeveloperController();
            boolean isRemove=testDeveloperController.delete(testDeveloperId);
            if (isRemove) {
                JOptionPane.showMessageDialog(this, "Test developer detail remove successfully!");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelRemoveTestDeveloperMouseClicked

    private void textTelephoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelephoneNoKeyReleased
        String telephoneNo=textTelephoneNo.getText();
        telephoneNo=telephoneNo.replaceAll("[\\D]", "");
        textTelephoneNo.setText(telephoneNo);        
    }//GEN-LAST:event_textTelephoneNoKeyReleased

    private void textNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNICKeyReleased
        String nic=textNIC.getText();
        nic=nic.replaceAll("[\\D&&[^v]&&[^x]]", "");
        textNIC.setText(nic);
    }//GEN-LAST:event_textNICKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelModifyTestDeveloper;
    private javax.swing.JLabel labelNIC;
    private javax.swing.JLabel labelRemoveTestDeveloper;
    private javax.swing.JLabel labelTelephoneNo;
    private javax.swing.JLabel labelTestDeveloperId;
    private javax.swing.JLabel labelTestDeveloperName;
    private javax.swing.JTextField textNIC;
    private javax.swing.JTextField textTelephoneNo;
    private javax.swing.JTextField textTestDeveloperId;
    private javax.swing.JTextField textTestDeveloperName;
    // End of variables declaration//GEN-END:variables

    private void searchTestDeveloperById() {
        String testDeveloperId=textTestDeveloperId.getText();
        try {
            TestDeveloperController testDeveloperController=ServerConnector.getServerConnector().getTestDeveloperController();
            if (this.testDeveloperId!=testDeveloperId) {
                testDeveloperController.releaseTestDeveloper(testDeveloperId);
            }
            this.testDeveloperId=testDeveloperId;
            TestDeveloperDTO testDeveloper=testDeveloperController.search(testDeveloperId);
            if (testDeveloper!=null) {
                if (testDeveloperController.reserveTestDeveloper(testDeveloperId)) {
                    textTestDeveloperName.setText(testDeveloper.getTestDeveloperName());
                    textNIC.setText(testDeveloper.getNic());
                    textTelephoneNo.setText(Integer.toString(testDeveloper.getTelephoneNo())); 
                } else {
                    JOptionPane.showMessageDialog(this, "This test developer is already reserved!");
                }                 
            } else {
                JOptionPane.showMessageDialog(this, "Not found test developer!");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchTestDeveloperByName() {
        String testDeveloperName=textTestDeveloperName.getText();
        int index=testDeveloperName.length();
        try {
            TestDeveloperController testDeveloperController=ServerConnector.getServerConnector().getTestDeveloperController();
            TestDeveloperDTO testDeveloper=testDeveloperController.searchByNameTestDeveloper(testDeveloperName);
            if (this.testDeveloperId!=testDeveloper.getTestDeveloperId()) {
                testDeveloperController.releaseTestDeveloper(testDeveloperId);
            }
            this.testDeveloperId=testDeveloper.getTestDeveloperId();
            if (testDeveloper!=null) {
                if (testDeveloperController.reserveTestDeveloper(testDeveloperId)) {
                    textTestDeveloperId.setText(testDeveloper.getTestDeveloperId());                
                    textTestDeveloperName.setText(testDeveloper.getTestDeveloperName());
                    textTestDeveloperName.select(index, 30);
                    textNIC.setText(testDeveloper.getNic());
                    textTelephoneNo.setText(Integer.toString(testDeveloper.getTelephoneNo()));    
                } else {
                    JOptionPane.showMessageDialog(this, "This test developer is already reserved!");
                }                            
            } else {
                JOptionPane.showMessageDialog(this, "Not found test developer!");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TestDeveloperManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (StringIndexOutOfBoundsException ex){}
    }
}
